neurolib-dev/neurolib

- neurolib/models/aln/loadDefaultParams.py
> Changed aln default parameters

- neurolib/models/aln/model.py
- neurolib/models/bold/model.py
- neurolib/models/hopf/model.py
use `super` and `self` where possible, I also get rid of unused imports
@caglorithm please check and merge when you'd find it ok
> Small class inheritance fixes

- README.md
- neurolib/optimize/evolution/deapUtils.py
- neurolib/optimize/evolution/evolution.py
- neurolib/optimize/evolution/evolutionaryUtils.py
- neurolib/utils/loadData.py
- tests/test_datasets.py
- tests/test_evolution.py
Removed unnecessary functions and added a few new testing cases for evolution utility functions and for datasets. Matplotlib lazy importing now.
> New testing cases

- neurolib/models/model.py
> fix in model superclass with init of parameters

- README.md
`Readme.md`: Better description of the evolutionary algorithm
> readme: fix evolutionary optimization description

- neurolib/models/thalamus/__init__.py
- neurolib/models/thalamus/loadDefaultParams.py
- neurolib/models/thalamus/model.py
- neurolib/models/thalamus/timeIntegration.py
- tests/test_models.py
Simple thalamic conductance-based mass model, due to Schellenberger Costa et al.
A bit different from other models, since this is a thalamus-only model, i.e. doesn't work within a network. So far without inputs from other areas.
Left to do:
Reference: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005022
> Thalamic mass model

- neurolib/models/thalamus/timeIntegration.py
> thalamus: firing rates kHz -> Hz conversion

- README.md
> Readme: update reference

- codecov.yml
- neurolib/optimize/exploration/explorationUtils.py
- tests/test_explorationUtils.py
> Increase testing coverage

- neurolib/models/aln/loadDefaultParams.py
- neurolib/models/aln/model.py
- neurolib/models/aln/timeIntegration.py
- tests/test_signal.py
**Model update:** 
`aln` now records adaptation currents.
> aln: record adaptation currents

- tests/test_autochunk.py
- tests/test_datasets.py
- tests/test_evolution.py
- tests/test_evolutionUtils.py
- tests/test_exploration.py
- tests/test_explorationUtils.py
- tests/test_functions.py
- tests/test_imports.py
- tests/test_notebooks.py
- tests/test_parameterspace.py
- tests/test_signal.py
quick PR for tidier tests:
* remove unused imports
* sort imports
* add `if __ name__ == ...` clause
* remove temp directory after testing with classmethod `tearDown`
> Tidy up tests

- neurolib/models/model.py
- neurolib/models/thalamus/loadDefaultParams.py
- neurolib/models/thalamus/model.py
- neurolib/models/thalamus/timeIntegration.py
- tests/multimodel/test_thalamus.py
- tests/test_autochunk.py
The thalamic model now works with `autochunk`. This was resolved by manually casting all necessary thalamic outputs into 2D.
> Fix: thalamus

- .github/workflows/python-package.yml
> Test: CI on GitHub

- examples/example-0.6-custom-model.ipynb
- tests/multimodel/test_fitzhugh_nagumo.py
- tests/multimodel/test_hopf.py
- tests/multimodel/test_thalamus.py
- tests/multimodel/test_wilson_cowan.py
- tests/multimodel/test_wong_wang.py
> Fix MultiModel tests

- examples/example-0.4-wc-minimal.ipynb
- neurolib/models/multimodel/builder/wilson_cowan.py
- neurolib/models/wc/loadDefaultParams.py
- neurolib/models/wc/timeIntegration.py
- neurolib/models/ww/__init__.py
- neurolib/models/ww/loadDefaultParams.py
- neurolib/models/ww/model.py
- neurolib/models/ww/timeIntegration.py
- setup.py
- tests/test_autochunk.py
- tests/test_models.py
* New model: Wong Wang 🚀
* Fix Wilson-Cowan parameter issues, closes #129 🛠
> New model: Wong Wang

- neurolib/models/multimodel/builder/base/network.py
- neurolib/models/multimodel/model.py
- tests/multimodel/base/test_network.py
- tests/multimodel/test_wilson_cowan.py
discovered when I was working with the thalamocortical motif (1 node ALN + thalamus).
Now all should be ok.
> Small MultiModel fixes

- neurolib/utils/signal.py
- tests/test_signal.py
Quickie: `Signal` class minor fix and minor addition:
> Signal minor fix

- neurolib/models/multimodel/model.py
> Smallest PR ever

- neurolib/optimize/exploration/exploration.py
User can chose the number of cores for exploration: 
```python
parameters = ParameterSpace({"parameter": parameter_values})
search = BoxSearch(evalFunction = run, parameterSpace = parameters, ncores=2)
```
> exploration: ncores argument

- neurolib/utils/functions.py
- tests/test_functions.py
This PR should significantly speed up the computation of Kuramoto order parameter.
Reference issue: #157
> Speed up kuramoto function

- examples/example-4-multimodel-intro.ipynb
- neurolib/models/multimodel/__init__.py
First `MultiModel` notebook:
- basic intro
- how the hierarchy works (basics)
- how parameters work
- how connecting two models works (ALN + thalamus)
(1st PR in #159)
> MultiModel notebooks: 1

- examples/example-4.2-multimodel-backends-and-optimization.ipynb
- neurolib/utils/stimulus.py
- tests/test_stimulus.py
Beast-mode for stimuli:
```python
ou = OrnsteinUhlenbeckProcess(mu=0.1, sigma=0.2, tau=2.0, num_iid=2)
sq = SquareInput(amplitude=0.2, period=60.0, num_iid=2)
sin = SinusoidalInput(amplitude=0.7, period=100.0, num_iid=2)
```
```python
summed = ou + sq + sin
```
```python
conc = ou & sq & sin
```
```python
conc = ConcatenatedInput([ou, sq, sin], length_ratios=[1, 2, 3])
```
```python
beast = (ou + sq) & (sq + sin)
```
```python
beast = ConcatenatedInput([ou + sq, ou + sin], [2, 5])
```
And so on...
> Stimulus: Concatenated vs. Summed

- neurolib/optimize/exploration/exploration.py
- neurolib/utils/stimulus.py
- tests/test_exploration.py
- tests/test_stimulus.py
quick bug fix:
now `MultiModel` exploration should work with custom evaluate function
> BoxSearch with custom evaluate function

- neurolib/optimize/evolution/evolution.py
simply wrap `evalFunction` in `try` - `except` block and log any exceptions
> Better error catching in evolution

- .github/workflows/documentation.yml
- docs/exploration/boxsearch.md
- mkdocs.yml
- neurolib/utils/parameterSpace.py
* Assume parameter space kind "grid" more broadly.
* Smuggled a documentation build fix into this PR as well.
> ParameterSpace: fix kind assumption & fix documentation

- examples/example-0-aln-minimal.ipynb
- examples/example-0.1-hopf-minimal.ipynb
- examples/example-0.2-basic_analysis.ipynb
- examples/example-0.3-fhn-minimal.ipynb
- examples/example-0.4-wc-minimal.ipynb
- examples/example-0.5-external-stimulus.ipynb
- examples/example-0.6-custom-model.ipynb
- examples/example-1-aln-parameter-exploration.ipynb
- examples/example-1.1-custom-parameter-exploration.ipynb
- examples/example-1.2-brain-network-exploration.ipynb
- examples/example-1.2.1-brain-exploration-postprocessing.ipynb
- examples/example-1.3-aln-bifurcation-diagram.ipynb
- examples/example-2-evolutionary-optimization-minimal.ipynb
- examples/example-2.0.1-save-and-load-evolution.ipynb
- examples/example-2.1-evolutionary-optimization-aln.ipynb
- examples/example-2.2-evolution-brain-network-aln-resting-state-fit.ipynb
- examples/example-3-meg-functional-connectivity.ipynb
Based on this> https://stackoverflow.com/a/71217353
> Hopefully fix docs CI errors

- examples/example-0-aln-minimal.ipynb
While going through the examples, I noticed some spelling mistakes and fixed them.
I hope it is okay to do it like this.
Thanks for the work and sharing the framework
> Fix spelling Example 0.0
