neurolib/optimize/evolution/evolution.py, neurolib/optimize/evolution/evolutionaryUtils.py, requirements.txt, tests/test_evolution.py, tests/test_evolutionUtils.py
* Load an evolution from disk that was previously saved using `dill`.
Saving:
```python
... # evolution done here
evolution.saveEvolution("data/evolution.dill")
```
Loading, in another session:
```python
evolution = Evolution(lambda x: x, ParameterSpace(['mock'],  [[0, 1]]))
evolution = evolution.loadEvolution("data/evolution.dill")
```
Because the objects are not serializable, I needed to use `dill` for saving and loading. This means, this would be a new dependency (which I' obviously trying to avoid as much as possible). At the same time, saving and loading a previous evolution / exploration is, I think, a very important feature and reinitializing the evolution with the loaded dill is a bit non-trivial, so I thought it makes sense to solve this issue for the user instead of letting them …
=> Load evolution from disk

examples/example-0.3-fhn-minimal.ipynb, neurolib/models/aln/loadDefaultParams.py, neurolib/models/fhn/loadDefaultParams.py, neurolib/models/thalamus/loadDefaultParams.py, neurolib/models/wc/loadDefaultParams.py, neurolib/optimize/evolution/evolution.py, setup.py
`pypet` doesn't like to add `None` results. The RNG seed parameter `model.params["seed"]` is usually `None` and was set to `0` to avoid issues before. Now it stays `None` but when saving to `pypet`, the case is handled.
The rest of the other changes are only black formatting...
=> evolution: handling of seed = None for pypet

.travis.yml, neurolib/models/multimodel/__init__.py, neurolib/models/multimodel/builder/base/backend.py, neurolib/models/multimodel/builder/base/constants.py, neurolib/models/multimodel/builder/base/network.py, neurolib/models/multimodel/builder/base/neural_mass.py, neurolib/models/multimodel/builder/hopf.py, neurolib/models/multimodel/builder/model_input.py, neurolib/utils/saver.py, requirements.txt, setup.py, tests/multimodel/base/test_backend.py, tests/multimodel/base/test_network.py, tests/multimodel/base/test_neural_mass.py, tests/multimodel/test_hopf.py, tests/multimodel/test_model_input.py
This PR contains the basic structure of MultiModels, i.e. hierarchical heterogeneous models building. 
Includes:
* base classes for three levels of hierarchy (`NeuralMass`, `Node`, `Network`) - of course the names are negotiable :)
* backend integrator (both `jitcdde`-based with adaptive `dt` and `numba` with Euler scheme)
* model input - for adding noise or stimuli to the models
* Hopf model - as an example of how various parts of the framework work together
* tests for all of the above written
* added packages to requirements
* altered `setup.py` - one package needs to be installed from github as the newest additions I am using are not tagged yet, hence not on `pypi` - this will change in the future I hope
I suggest the following order of review:
1. …
=> MultiModel PR 1

neurolib/models/multimodel/builder/base/network.py, neurolib/models/multimodel/builder/fitzhugh_nagumo.py, neurolib/models/multimodel/builder/hopf.py, neurolib/models/multimodel/builder/thalamus.py, neurolib/models/multimodel/builder/wilson_cowan.py, neurolib/models/multimodel/builder/wong_wang.py, neurolib/models/wc/timeIntegration.py, neurolib/optimize/evolution/evolution.py, tests/multimodel/base/test_backend.py, tests/multimodel/base/test_network.py, tests/multimodel/base/test_neural_mass.py, tests/multimodel/test_fitzhugh_nagumo.py, tests/multimodel/test_hopf.py, tests/multimodel/test_thalamus.py, tests/multimodel/test_wilson_cowan.py, tests/multimodel/test_wong_wang.py, tests/test_evolution.py
The second PR of the MultiModel framework, now we know how the internals and model building works so this one should be quick -- introducing different models:
* FitzHugh-Nagumo
* thalamic mass model due to Costa et al.
* Wilson-Cowan
* Wong-Wang (both excitatory vs inhibitory version of `Node` - as Wilson-Cowan and Reduced version of `Node` with one mass - as FitzHugh-Nagumo)
(Side note - our holy grail - AdEx model - will follow in PR3 as it is more complicated to define since it involves table lookup and it's tricky to do that in symbolic derivatives).
All models are tested - whether they can be initialised, they are run with both backend and their output compared and moreover they are tested against `neurolib`'s native implementation (with exception of Wong-Wang since it's not in the …
=> MultiModel PR2: base models

.github/workflows/ci.yml, neurolib/models/multimodel/builder/base/backend.py, tests/multimodel/base/test_backend.py, tests/test_autochunk.py
Remove unused options for `jitcdde` backend:
* OpenMP support - `jitcdde` can use OpenMP for compiling symbolic equations into C. However, this comes with tremendous overhead and while I was testing this, OpenMP does not offer almost any speedup
* save / load compiled - there is an option to save compiled C code of the equations and then just load it on next run. In theory, this would significantly speed up computations of large networks where the compilation to C takes a lot of time. However, our code works in a way that parameter values are "hardcoded" into symbolic computation, hence on each parameter change (imagine exploration), we would need to compile again. And therefore I cannot see any use case of this as of now.
=> Simplify `jitcdde` backend

neurolib/models/multimodel/builder/aln.py, neurolib/models/multimodel/builder/base/constants.py, neurolib/models/multimodel/builder/base/network.py, neurolib/models/multimodel/builder/base/neural_mass.py, neurolib/models/multimodel/builder/model_input.py, neurolib/models/multimodel/builder/thalamus.py, neurolib/models/multimodel/model.py, neurolib/optimize/evolution/evolution.py, neurolib/optimize/exploration/exploration.py, neurolib/utils/parameterSpace.py, tests/multimodel/base/test_network.py, tests/multimodel/base/test_neural_mass.py, tests/multimodel/test_fitzhugh_nagumo.py, tests/multimodel/test_hopf.py, tests/multimodel/test_model_input.py, tests/multimodel/test_thalamus.py, tests/multimodel/test_wilson_cowan.py, tests/multimodel/test_wong_wang.py, tests/test_autochunk.py, tests/test_exploration.py, tests/test_parameterspace.py
- same name for firing rate in `ALN` and `thalamus` models
- better handling of connectivity in `_additive_coupling()` and `_diffusive_coupling()` helpers
- allow `None` in `_construct_input_matrix()` helper as an option for a node to not couple anywhere (useful when the whole network has a different coupling for each node, e.g. thalamus has network `exc -> inh` coupling, but ALN does not)
- some changes in parameter handling:
- change names in the overall parameter list to mass / node label so you can change all parameter of the all instances of the same type (e.g. `ALN`)
- update parameters in the noise inputs (for some reason I forgot to add this before...)
- `ParameterSpace` class now have `allow_star_notation` keyword which allows to track little changes in `Exploration` class (e.g. …
=> MultiModel small changes & Exploration fix

neurolib/utils/collections.py, tests/test_collections.py
Star notation was always part of the MultiModel (getting all keys based on "*" in parameter dict). Now, filtering also works. Example:
```python
model.params["*tau"]
{'WCnode_0.WCmassEXC_0.tau': 2.5,
'WCnode_0.WCmassEXC_0.noise_0.tau': 5.0,
'WCnode_0.WCmassINH_1.tau': 3.75,
'WCnode_0.WCmassINH_1.noise_0.tau': 5.0}
```
so we obtained all `tau` parameters - time scales for both masses in Wilson-Cowan model, but also time scales of Ornstein-Uhlenbeck noise... but:
```python
model.params["*tau|noise"]
{'WCnode_0.WCmassEXC_0.tau': 2.5, 'WCnode_0.WCmassINH_1.tau': 3.75}
```
Note: draft for now, I need to add some small things to `Evolution` due to this
=> Support filtering from MultiModel parameters

neurolib/models/multimodel/model.py, neurolib/utils/collections.py, tests/test_collections.py
Last step before ALN+thalamus motif evolution. 
The tricky part was to optimize with respect to connectivity. Because connectivity is a matrix, and AFAIK you cannot parameterize matrix within evolution framework in neurolib. So I used a "trick":
- I added parameters to `model.params` such as `model.params["aln_thal"]` and `model.params["thal_aln"]` for both connection strengths - now they are floats, so evaluation (`deap`) can work with them
- inside the `evaluateSimulation` function I created explicitly a connectivity matrix as `np.array([[0.0, model.params["thal_aln"]], [model.params["aln_thal"], 0.0]])`
- I assign this connectivity to the model
But it was not working. This is because of another MultiModel trait: usage of "star" notation. I was using `unwrap_star_dotdict` from …
=> MultiModel evolution: allow "extra" keys

neurolib/models/multimodel/builder/__init__.py, neurolib/models/multimodel/builder/aln.py, neurolib/models/multimodel/builder/base/backend.py, neurolib/models/multimodel/builder/base/network.py, neurolib/models/multimodel/builder/base/neural_mass.py, neurolib/models/multimodel/builder/base/params.py, tests/multimodel/base/test_backend.py, tests/multimodel/base/test_network.py, tests/multimodel/base/test_params.py, tests/multimodel/test_aln.py
A newer and shiny `numba` backend to MultiModel.
Before: 
- each new model parameters meant a new compilation since model parameters were directly inserted as floats into symbolic equations
Now:
- when using `numba` backend, all parameters are transformed to `sp.Symbol`, used function arguments for `numba`-jitted `integrate` function
- therefore when parameters change, no new compilation is needed
Apart from the new `numba` backend, I had to make some small changes to the existing code. In order to make this easier for you, I'll comment directly into the code below.
=> MultiModel Chad-numba backend

neurolib/models/multimodel/builder/base/backend.py, neurolib/models/multimodel/model.py, tests/multimodel/base/test_backend.py, tests/test_models.py
`MultiModel` now able to accommodate continuous runs with `model.run(continue_run=True)`. It'll set initial state from previous run(s).
Naturally, one can change parameters between runs, and, moreover, one can also change (noise) inputs in between runs. 
E.g. one can start the ALN model with no noise for 2 seconds, then continue with Ornstein-Uhlenbeck and finally end it with sinusoidal input. Of course, one can change parameters in between.
Moreover, one last addition: some shortcuts for ease of access:
`model.num_state_variables` - return total number of state variables in the `MultiModel`
`model.num_noise_variables` - return the total number of variables that accept noise (e.g. in ALN node it's 2)
`model.noise_input` - return or set the full input to the model (list of length …
=> MultiModel continue run

neurolib/models/multimodel/builder/aln.py, neurolib/models/multimodel/model.py
quick fix in rescaling connectivity on parameter update in MultiModel's ALN
=> QFix: Rescaling connectivity in ALN MultiModel

neurolib/optimize/exploration/exploration.py, tests/test_exploration.py
Two separate bugs in `xr()` function of `BoxSearch` when using `MultiModel` and star parameters:
1. sometimes `xr.combine_by_coords` fails with a cryptic error, found this (https://github.com/pydata/xarray/issues/3248#issuecomment-531511177) and it seems that this might happen when combining DataArrays, but shouldn't happen on Datasets
2. `ParameterSpace` for `MultiModel` might contain stars. but not necessarily, and line 533 was giving problems when exploring over a parameter without a star... now explicitly checking for this
3.  sanitize variable names and attributes - `xarray` is fine with whatever, but when saving to netcdf, `*`, `|` are not permitted
=> Quick fixes for BoxSearch xr() when exploring MultiModel

neurolib/models/thalamus/model.py, neurolib/models/thalamus/timeIntegration.py
Two minor things I encountered when working on my thalamus-aln implementation.
**Seed not set**
Seed given as argument was not set if the constructor called `loadDefaultParams()`
```python
model = ThalamicMassModel(seed=42)
print(model.params["seed"])  # --> None
```
**Index out of bounds in `noise`**
`noise` has the size `len(t)` whilst `i` goes over `range(startind, startind + len(t))`.
=> Minor fixes: setting seed + avoiding index out of bounds for noise array

neurolib/models/fhn/timeIntegration.py, neurolib/models/hopf/timeIntegration.py, neurolib/models/wc/timeIntegration.py, neurolib/models/ww/timeIntegration.py
x_ou, y_ou and exc_ou, inh_ou variables overwrite corresponding params, include ".copy()" to fix this
=> fixed bug in fhn, hopf, wc, ww models: copy params

neurolib/models/fhn/timeIntegration.py, neurolib/models/hopf/timeIntegration.py, neurolib/models/wc/timeIntegration.py, neurolib/models/ww/timeIntegration.py
This PR removes `params["Dmat_ndt"] = Dmat_ndt` as a parameter from the FHN, Hopf, WC, WW models because `Dmat_ndt` is derived from `lengthMat` and is not a parameter that should be set by the user.
=> removed Dmat_ndt as param set in timeIntegration file

neurolib/models/aln/loadDefaultParams.py, neurolib/models/aln/timeIntegration.py, neurolib/models/fhn/loadDefaultParams.py, neurolib/models/fhn/timeIntegration.py, neurolib/models/hopf/loadDefaultParams.py, neurolib/models/hopf/timeIntegration.py, neurolib/models/wc/loadDefaultParams.py, neurolib/models/wc/timeIntegration.py, neurolib/models/ww/loadDefaultParams.py, neurolib/models/ww/timeIntegration.py, neurolib/utils/model_utils.py
computeDelayMatrix is the same for aln, fhn, hopf, wc, ww model
moved function to model_utils.py to avoid code duplication
=> moved computedelaymatrix function to /utils/model_utils

neurolib/models/multimodel/builder/base/backend.py, neurolib/models/multimodel/builder/base/network.py, neurolib/models/multimodel/model.py, neurolib/utils/parameterSpace.py, neurolib/utils/signal.py, tests/multimodel/base/test_network.py
`np.float`, `np.object`, and similar don't exist anymore, so fix it
=> Fix numpy new version errors

neurolib/models/aln/timeIntegration.py
... as discussed with Nikola :-)
=> corrected index of rates_exc in computation of IA_rhs

neurolib/models/aln/model.py, tests/test_autochunk.py
added "ext_inh_current" and "ext_inh_rate" to input_vars of aln
adapt test_autochunk accordingly
=> aln input_vars

neurolib/models/ww/timeIntegration.py
Hello, I observed a discrepancy in analysis using models.ww when compared to analysis from another implementation. Further experimentation led me to notice the steady state values were different from the analytical solution (in the non-stochastic case). Luckily, I was able to identify the source of the issue, which was simply setting tau_inh incorrectly in models.ww.timeIntegration. Hopefully this can be merged quickly. Thank you!
=> Bug Fix: Setting value of tau_inh in timeIntegration

tests/control/optimal_control/test_oc.py, tests/control/optimal_control/test_oc_fhn.py
- added tests for so far uncovered functions
- moved static functions and parameters to test_oc_utils
=> Revise control tests

neurolib/control/optimal_control/oc_fhn/oc_fhn.py, neurolib/control/optimal_control/oc_hopf/oc_hopf.py, neurolib/models/fhn/timeIntegration.py, neurolib/models/hopf/timeIntegration.py
network jacobian was not computed correctly for diffusive coupling in fhn and hopf model
=> Fix bug in fhn and hopf OC

neurolib/control/optimal_control/cost_functions.py, neurolib/control/optimal_control/oc.py, tests/control/optimal_control/test_oc_cost_functions.py
implement in cost functionals
include in weight dictionary
tests
=> Directional sparsity cost functional

neurolib/models/bold/timeIntegration.py
When using `simulateBOLD()` externally with default initialization, the `F` vector is set to zeros, which throws a division by zero error down the line in numba. 
This can be avoided by setting F with a small epsilon before using it in the calculation of other state variables.  
Might be related to issue #250.
=> BOLD initialization : avoid divide by zero with default params
